import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import api from '../api/axiosInstance';

const ReportExport = () => {
    const navigate = useNavigate();
    const { t } = useTranslation();
    const [loading, setLoading] = useState({});
    const [farms, setFarms] = useState([]);
    const [advisories, setAdvisories] = useState([]);
    const [diseaseHistory, setDiseaseHistory] = useState([]);
    const [yieldHistory, setYieldHistory] = useState([]);

    useEffect(() => {
        if (!localStorage.getItem('token')) navigate('/login');
        fetchData();
    }, [navigate]);

    const fetchData = async () => {
        try {
            const [farmsRes, advisoryRes, diseaseRes, yieldRes] = await Promise.all([
                api.get('/api/farms'),
                api.get('/api/advisories/history'),
                api.get('/api/disease/history'),
                api.get('/api/yield/history'),
            ]);
            setFarms(farmsRes.data);
            setAdvisories(advisoryRes.data);
            setDiseaseHistory(diseaseRes.data);
            setYieldHistory(yieldRes.data);
        } catch { /* some might fail if no data */ }
    };

    const downloadCSV = (data, filename, headers) => {
        if (!data.length) return alert(t('No data to export'));
        const csvRows = [headers.join(',')];
        data.forEach(row => {
            const values = headers.map(h => {
                const val = row[h.toLowerCase().replace(/ /g, '_')] ?? row[h] ?? '';
                return `"${String(val).replace(/"/g, '""')}"`;
            });
            csvRows.push(values.join(','));
        });
        const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = filename; a.click();
        URL.revokeObjectURL(url);
    };

    const downloadPDF = (title, content) => {
        // Simple HTML-to-PDF using print
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>${title} - KrishiMitra Report</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
                    h1 { color: #15803d; border-bottom: 2px solid #15803d; padding-bottom: 10px; }
                    h2 { color: #1f2937; margin-top: 30px; }
                    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
                    th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; font-size: 13px; }
                    th { background: #f0fdf4; color: #15803d; font-weight: 600; }
                    tr:nth-child(even) { background: #f9fafb; }
                    .header { display: flex; justify-content: space-between; align-items: center; }
                    .date { color: #6b7280; font-size: 13px; }
                    .footer { margin-top: 40px; border-top: 1px solid #d1d5db; padding-top: 10px; color: #9ca3af; font-size: 11px; text-align: center; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>KrishiMitra - ${title}</h1>
                    <span class="date">Generated: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
                </div>
                ${content}
                <div class="footer">Report generated by KrishiMitra Smart Crop Advisory System</div>
            </body>
            </html>
        `);
        printWindow.document.close();
        setTimeout(() => { printWindow.print(); }, 500);
    };

    const exportFarmsCSV = () => {
        downloadCSV(farms, 'farms_report.csv', ['farm_name', 'current_crop', 'area_acres', 'soil_type', 'soil_ph', 'irrigation_type', 'district', 'state', 'sowing_date']);
    };

    const exportFarmsPDF = () => {
        const rows = farms.map(f => `<tr><td>${f.farm_name}</td><td>${f.current_crop}</td><td>${f.area_acres}</td><td>${f.soil_type}</td><td>${f.soil_ph || '-'}</td><td>${f.irrigation_type || '-'}</td><td>${f.district || '-'}, ${f.state || '-'}</td></tr>`).join('');
        downloadPDF('Farm Report', `
            <h2>Registered Farms (${farms.length})</h2>
            <table><tr><th>Farm</th><th>Crop</th><th>Acres</th><th>Soil</th><th>pH</th><th>Irrigation</th><th>Location</th></tr>${rows}</table>
        `);
    };

    const exportAdvisoriesCSV = () => {
        downloadCSV(advisories, 'advisories_report.csv', ['nitrogen', 'phosphorous', 'potassium', 'temperature', 'humidity', 'ph', 'rainfall', 'crop_recommendation', 'fertilizer_advice', 'created_at']);
    };

    const exportAdvisoriesPDF = () => {
        const rows = advisories.slice(0, 20).map(a => `<tr><td>${a.nitrogen}/${a.phosphorous}/${a.potassium}</td><td>${a.temperature}°C</td><td>${a.humidity}%</td><td>${a.ph}</td><td>${a.rainfall}mm</td><td>${a.crop_recommendation}</td><td style="max-width:200px">${a.fertilizer_advice}</td><td>${new Date(a.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('');
        downloadPDF('Advisory Report', `
            <h2>Crop Advisories (Last ${Math.min(advisories.length, 20)})</h2>
            <table><tr><th>NPK</th><th>Temp</th><th>Humidity</th><th>pH</th><th>Rain</th><th>Crop Rec.</th><th>Fertilizer Advice</th><th>Date</th></tr>${rows}</table>
        `);
    };

    const exportDiseaseCSV = () => {
        downloadCSV(diseaseHistory, 'disease_history.csv', ['predicted_disease', 'confidence', 'treatment', 'low_confidence', 'created_at']);
    };

    const exportDiseasePDF = () => {
        const rows = diseaseHistory.slice(0, 20).map(d => `<tr><td>${d.predicted_disease}</td><td>${d.confidence}%</td><td style="max-width:250px">${d.treatment || '-'}</td><td>${d.low_confidence ? 'Yes' : 'No'}</td><td>${new Date(d.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('');
        downloadPDF('Disease Detection Report', `
            <h2>Disease Detection History (Last ${Math.min(diseaseHistory.length, 20)})</h2>
            <table><tr><th>Disease</th><th>Confidence</th><th>Treatment</th><th>Low Conf?</th><th>Date</th></tr>${rows}</table>
        `);
    };

    const exportYieldCSV = () => {
        downloadCSV(yieldHistory, 'yield_predictions.csv', ['crop', 'area_acres', 'predicted_yield_kg', 'yield_per_acre', 'confidence', 'harvest_window_start', 'harvest_window_end', 'created_at']);
    };

    const exportYieldPDF = () => {
        const rows = yieldHistory.slice(0, 20).map(y => `<tr><td>${y.farm_name || '-'}</td><td>${y.crop}</td><td>${y.area_acres}</td><td>${y.predicted_yield_kg?.toLocaleString()} kg</td><td>${y.yield_per_acre?.toLocaleString()} kg/ac</td><td>${y.confidence}</td><td>${y.harvest_window_start ? new Date(y.harvest_window_start).toLocaleDateString('en-IN') : '-'} — ${y.harvest_window_end ? new Date(y.harvest_window_end).toLocaleDateString('en-IN') : '-'}</td></tr>`).join('');
        downloadPDF('Yield Prediction Report', `
            <h2>Yield Predictions (Last ${Math.min(yieldHistory.length, 20)})</h2>
            <table><tr><th>Farm</th><th>Crop</th><th>Acres</th><th>Yield</th><th>Per Acre</th><th>Confidence</th><th>Harvest Window</th></tr>${rows}</table>
        `);
    };

    const reportSections = [
        {
            title: t('Farm Details'),
            description: t('report_farm_desc'),
            count: farms.length,
            color: 'border-l-green-500',
            iconBg: 'bg-[#ecfdf5] text-[#065f46]',
            onCSV: exportFarmsCSV,
            onPDF: exportFarmsPDF,
        },
        {
            title: t('Crop Advisories'),
            description: t('report_advisory_desc'),
            count: advisories.length,
            color: 'border-l-blue-500',
            iconBg: 'bg-blue-50 text-blue-700',
            onCSV: exportAdvisoriesCSV,
            onPDF: exportAdvisoriesPDF,
        },
        {
            title: t('Disease Detections'),
            description: t('report_disease_desc'),
            count: diseaseHistory.length,
            color: 'border-l-red-500',
            iconBg: 'bg-red-50 text-red-700',
            onCSV: exportDiseaseCSV,
            onPDF: exportDiseasePDF,
        },
        {
            title: t('Yield Predictions'),
            description: t('report_yield_desc'),
            count: yieldHistory.length,
            color: 'border-l-purple-500',
            iconBg: 'bg-purple-50 text-purple-700',
            onCSV: exportYieldCSV,
            onPDF: exportYieldPDF,
        },
    ];

    return (
        <div className="page-content">
                <div className="page-header">
                    <h1 className="page-title">{t('Reports & Export')}</h1>
                    <p className="page-subtitle">{t('Download your farming data as PDF or CSV files')}</p>
                </div>

                <div className="space-y-4">
                    {reportSections.map((section, idx) => (
                        <div key={idx} className={`bg-white border border-gray-200 border-l-4 ${section.color} rounded-xl shadow-sm p-6`}>
                            <div className="flex items-center justify-between">
                                <div className="flex-1">
                                    <div className="flex items-center gap-2 mb-1">
                                        <h3 className="text-base font-semibold text-[#1a2e2a]">{section.title}</h3>
                                        <span className="bg-gray-100 text-[#4b6360] px-2 py-0.5 rounded-full text-xs font-medium">
                                            {section.count} {t('records')}
                                        </span>
                                    </div>
                                    <p className="text-sm text-[#6b7280]">{section.description}</p>
                                </div>
                                <div className="flex gap-2 ml-4">
                                    <button onClick={section.onCSV} disabled={section.count === 0}
                                        className="flex items-center gap-1.5 px-4 py-2 bg-gray-100 hover:bg-gray-200 text-[#374151] rounded-lg text-sm font-medium transition-colors disabled:opacity-40">
                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                                        {t('CSV')}
                                    </button>
                                    <button onClick={section.onPDF} disabled={section.count === 0}
                                        className="flex items-center gap-1.5 px-4 py-2 bg-[#065f46] hover:bg-[#059669] text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-40">
                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                                        {t('PDF')}
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Full Report */}
                <div className="mt-6 glass-card rounded-2xl p-6 text-center">
                    <h3 className="text-base font-semibold text-[#1a2e2a] mb-2">{t('Complete Farm Report')}</h3>
                    <p className="text-sm text-[#6b7280] mb-4">{t('complete_report_desc')}</p>
                    <button
                        onClick={() => {
                            const allContent = `
                                <h2>Farms (${farms.length})</h2>
                                <table><tr><th>Farm</th><th>Crop</th><th>Acres</th><th>Soil</th><th>Location</th></tr>${farms.map(f => `<tr><td>${f.farm_name}</td><td>${f.current_crop}</td><td>${f.area_acres}</td><td>${f.soil_type}</td><td>${f.district || '-'}, ${f.state || '-'}</td></tr>`).join('')}</table>
                                <h2>Recent Advisories (${Math.min(advisories.length, 10)})</h2>
                                <table><tr><th>NPK</th><th>pH</th><th>Recommendation</th><th>Date</th></tr>${advisories.slice(0, 10).map(a => `<tr><td>${a.nitrogen}/${a.phosphorous}/${a.potassium}</td><td>${a.ph}</td><td>${a.crop_recommendation}</td><td>${new Date(a.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('')}</table>
                                <h2>Disease Detections (${Math.min(diseaseHistory.length, 10)})</h2>
                                <table><tr><th>Disease</th><th>Confidence</th><th>Treatment</th><th>Date</th></tr>${diseaseHistory.slice(0, 10).map(d => `<tr><td>${d.predicted_disease}</td><td>${d.confidence}%</td><td>${d.treatment || '-'}</td><td>${new Date(d.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('')}</table>
                            `;
                            downloadPDF('Complete Farm Report', allContent);
                        }}
                        disabled={farms.length === 0}
                        className="bg-[#065f46] hover:bg-[#059669] text-white px-8 py-3 rounded-lg text-sm font-medium transition-colors disabled:opacity-40">
                        {t('Generate Complete Report (PDF)')}
                    </button>
                </div>
            </div>
    );
};

export default ReportExport;
